export const languageArray = {
  "home-menu": {
    en: "home",
    pl: "strona główna",
    ru: "главная",
    ua: "головна",
  },
  "about-menu": {
    en: "about me",
    pl: "o mnie",
    ru: "обо мне",
    ua: "про мене",
  },
  "projects-menu": {
    en: "projects",
    pl: "projekty",
    ru: "проекты",
    ua: "проєкти",
  },
  "contact-menu": {
    en: "contact",
    pl: "kontakt",
    ru: "контакт",
    ua: "контакт",
  },
  hey: {
    en: "Hey, I am Olena Kim",
    pl: "Cześć, jestem Olena Kim",
    ru: "Привет, я Елена Ким",
    ua: "Привіт, я Олена Кім",
  },
  "welcome-text": {
    en: "Welcome to my portfolio! As a frontend developer skilled in HTML, CSS, JavaScript, and React.js, I craft dynamic and visually appealing web experiences. Explore my projects to see how I blend these technologies to create seamless user interfaces. Let's collaborate to bring your ideas to life!",
    pl: "Witaj na moim portfolio! Jako frontend developer z umiejętnościami w HTML, CSS, JavaScript oraz React.js, tworzę dynamiczne i atrakcyjne wizualnie strony internetowe. Zapoznaj się z moimi projektami, aby zobaczyć, jak łączę te technologie, tworząc płynne interfejsy użytkownika. Dajmy wspólnie życie Twoim pomysłom!",
    ru: "Добро пожаловать в мое портфолио! Как фронтенд-разработчик с навыками в HTML, CSS, JavaScript и React.js, я создаю динамичные и визуально привлекательные веб-приложения. Изучите мои проекты, чтобы увидеть, как я сочетаю эти технологии для создания плавных пользовательских интерфейсов. Давайте сотрудничать, чтобы воплотить ваши идеи в жизнь!",
    ua: "Ласкаво прошу до мого портфоліо! Як фронтенд-розробник з вміннями в HTML, CSS, JavaScript та React.js, я створюю динамічні та візуально привабливі веб-додатки. Дослідіть мої проекти, щоб побачити, як я поєдную ці технології для створення плавних користувацьких інтерфейсів. Давайте співпрацювати, щоб реалізувати ваші ідеї!",
  },
  development: {
    en: "development",
    pl: "programowanie",
    ru: "разработка",
    ua: "розробка",
  },
  hobbies: {
    en: "hobbies",
    pl: "zainteresowania",
    ru: "увлечения",
    ua: "хобі",
  },
  work: {
    en: "work",
    pl: "praca",
    ru: "работа",
    ua: "робота",
  },
  work: {
    en: "work",
    pl: "praca",
    ru: "работа",
    ua: "робота",
  },
  developmentText: {
    en: "In 2022, I completed a Computer Science course based on the Stanford CSA106 curriculum, focusing on Java. These courses provided me with a solid foundation before delving deeper into programming. Following that, in 2023, I enrolled in a Fullstack Developer course, which lasted approximately 10 months. During this time, I acquired skills in JavaScript programming, as well as mastering HTML, CSS, React.js, Node.js, and TypeScript. Additionally, I became proficient in utilizing various libraries such as Redux, Material UI, Formik, Axios, Toaster, and many others. Although I had a predisposition for programming back in school, it wasn't until 2022 that I realized my passion for advancing in and working within this field.",
    pl: "W 2022 roku ukończyłam kurs Computer Science oparty na programie Stanford CSA106, skupiający się na Javie. Te kursy dały mi solidne podstawy przed zagłębieniem się w programowanie. Następnie, w 2023 roku, zapisałam się na kurs Fullstack Developer, który trwał około 10 miesięcy. W tym czasie zdobyłam umiejętności programowania w JavaScript, a także opanowałem HTML, CSS, React.js, Node.js i TypeScript. Dodatkowo, stałam się biegła w wykorzystywaniu różnych bibliotek, takich jak Redux, Material UI, Formik, Axios, Toaster i wiele innych. Chociaż miałam predyspozycję do programowania jeszcze w szkole, to dopiero w 2022 roku zdałam sobie sprawę z mojej pasji do rozwoju i pracy w tej dziedzinie.",
    ru: "В 2022 году я завершила курс по компьютерной науке на основе учебного плана Stanford CSA106, с акцентом на Java. Эти курсы дали мне прочные основы перед погружением в программирование. После этого, в 2023 году, я поступила на курс Fullstack Developer, который продолжался около 10 месяцев. За это время я освоила навыки программирования на JavaScript, а также овладела HTML, CSS, React.js, Node.js и TypeScript. Кроме того, я стала опытной в использовании различных библиотек, таких как Redux, Material UI, Formik, Axios, Toaster и многих других. Хотя у меня уже была предрасположенность к программированию в школе, но только в 2022 году я осознала свою страсть к развитию и работе в этой области.",
    ua: "У 2022 році я завершила курс з комп'ютерних наук на основі навчальної програми Stanford CSA106, з акцентом на Java. Ці курси дали мені міцні основи перед поглибленням у програмування. Після цього, у 2023 році я записалась на курс Fullstack Developer, який тривав приблизно 10 місяців. За цей час я здобула навички програмування на JavaScript, а також оволоділа HTML, CSS, React.js, Node.js та TypeScript. Додатково, я стала вправною у використанні різноманітних бібліотек, таких як Redux, Material UI, Formik, Axios, Toaster та багатьох інших. Хоча в мене вже була схильність до програмування ще в школі, але лише у 2022 році я усвідомила свою пристрасть до розвитку і роботи у цій галузі.",
  },
  techSkills: {
    en: "My tech skills",
    pl: "Moje umiejętności techniczne",
    ru: "Мои технические навыки",
    ua: "Мої технічні навички",
  },
  diploma: {
    en: "computer science diploma",
    pl: "dyplom computer science",
    ru: "диплом computer science",
    ua: "диплом computer science",
  },
  certificate: {
    en: "fullstack developer certificate",
    pl: "certyfikat fullstack developer",
    ru: "сертификат fullstack developer",
    ua: "сертифікат fullstack developer",
  },
  workText: {
    en: "Currently, I work as an Expert in Mortgage Loan Launch at PKO Bank Polski. I've been with the Bank since 2018, right after completing my studies. Initially, I started as an administrator in the deposit account servicing team, and after a year, I transferred to the mortgage loan team, where I've been working ever since.<br/>Throughout my career, I've had the opportunity not only to perform operational tasks but also to participate in the development of programs aimed at improving and automating processes. My most significant project involved creating a program primarily based on OCR technology. This program streamlined the work of administrators, increased productivity, and reduced the risk of errors during operations. In this project, I served as a business analyst, documenting requirements, explaining connections between programs to developers, supervising task execution, testing the program, and conducting training for employees. This project provided me with invaluable experience and sparked my interest in development. In addition to this project, I regularly participate in manual testing of innovations, monitor processes, advocate for development and automation, and conduct training for other employees.",
    pl: "Aktualnie pracuję jako Ekspert ds. Uruchomienia Kredytów Hipotecznych w PKO Bank Polski. Pracuję w Banku od 2018 roku, zaraz po ukończeniu studiów. Początkowo rozpoczęłam pracę jako administrator w zespole obsługi rachunków depozytowych, a po roku przeniosłam się do zespołu kredytów hipotecznych, gdzie pracuję od tego czasu.<br/>W trakcie mojej kariery miałam okazję nie tylko wykonywać zadania operacyjne, ale także uczestniczyć w opracowywaniu programów mających na celu usprawnienie i zautomatyzowanie procesów. Mój najważniejszy projekt polegał na stworzeniu programu głównie opartego na technologii OCR. Ten program usprawnił pracę administratorów, zwiększył produktywność i zmniejszył ryzyko popełniania błędów podczas operacji. W ramach tego projektu pełniłem funkcję analityka biznesowego, dokumentując wymagania, wyjaśniając połączenia między programami deweloperom, nadzorując realizację zadań, testując program i prowadząc szkolenia dla pracowników. Ten projekt dostarczył mi bezcenne doświadczenie i rozbudził moje zainteresowanie programowaniem. Oprócz tego projektu regularnie uczestniczę w manualnym testowaniu innowacji, monitoruję procesy, wnioskuję o rozwój i automatyzację oraz prowadzę szkolenia dla innych pracowników.",
    ru: "В настоящее время я работаю экспертом по запуску ипотечных кредитов в PKO Bank Polski. Я работаю в банке с 2018 года, сразу после окончания учебы. Изначально я начала свою карьеру в роли администратора в команде обслуживания депозитных счетов, а через год перешела в команду ипотечных кредитов, где и работаю до сих пор.<br/>За время своей карьеры у меня была возможность не только выполнять операционные задачи, но и участвовать в разработке программ с целью улучшения и автоматизации процессов. Мой самый значимый проект заключался в создании программы, в основном основанной на технологии OCR. Эта программа оптимизировала работу администраторов, повысила производительность и снизила риск ошибок во время операций. В рамках этого проекта я выступала в роли бизнес-аналитика, документируя требования, объясняя связи между программами разработчикам, контролируя выполнение задач, тестируя программу и проводя тренинги для сотрудников. Этот проект дал мне бесценный опыт и возбудил мой интерес к разработке. Помимо этого проекта, я регулярно участвую в мануальном тестировании инноваций, отслеживаю процессы, выступаю за развитие и автоматизацию, и провожу тренинги для других сотрудников.",
    ua: "Зараз я працюю як експерт з запуску іпотечних кредитів в PKO Bank Polski. Я працюю в банку з 2018 року, одразу після закінчення навчання. Спочатку я почала працювати адміністратором у команді обслуговування депозитних рахунків, а через рік перейшла у команду іпотечних кредитів, де і працюю до цього часу.<br/>Протягом моєї кар'єри у мене була можливість не лише виконувати оперативні завдання, але й брати участь у розробці програм з метою поліпшення та автоматизації процесів. Мій найбільш значущий проект полягав у створенні програми, в основному заснованої на технології OCR. Ця програма оптимізувала роботу адміністраторів, підвищила продуктивність та знизила ризик помилок під час операцій. У рамках цього проекту я виступала у ролі бізнес-аналітика, документуючи вимоги, пояснюючи зв'язки між програмами розробникам, контролюючи виконання завдань, тестуючи програму та проводячи тренінги для співробітників. Цей проект надав мені безцінний досвід і розвинув мій інтерес до розробки. Окрім цього проекту, я регулярно беру участь у мануальному тестуванні інновацій, відстежую процеси, виступаю за розвиток та автоматизацію, і проводжу тренінги для інших співробітників.",
  },
  pianoText: {
    en: "I've been learning to play the piano since December 2023. I have a passion for listening to instrumental music.",
    pl: "Uczę się grać na pianinie od grudnia 2023 roku. Mam pasję do słuchania muzyki instrumentalnej.",
    ru: "Я учусь играть на пианино с декабря 2023 года. У меня есть страсть к прослушиванию инструментальной музыки.",
    ua: "Я вчуся грати на піаніно з грудня 2023 року. Маю пасію до слухання інструментальної музики.",
  },
  bookText: {
    en: "In my free time, I enjoy reading books. Additionally, I have a creative side where I craft handmade book covers, imbuing them with my own vision of aesthetics inspired by the books I've read.",
    pl: "W wolnym czasie lubię czytać książki. Ponadto, mam też kreatywną stronę, gdzie tworzę ręcznie robione okładki książek, nadając im moje własne spojrzenie na estetykę, zainspirowane przeczytanymi książkami.",
    ru: "В свободное время я люблю читать книги. Кроме того, у меня есть творческая сторона, где я создаю рукодельные обложки для книг, воплощая в них своё видение эстетики и вдохновение, полученные из прочитанных произведений.",
    ua: "У вільний час я люблю читати книги. Крім того, у мене є творчий бік, де я створюю ручні обкладинки для книг, надаючи їм моє власне бачення естетики, вдохновлене прочитаними книгами.",
  },
};
